import { ReactNode } from "react";
import { FieldValue } from "firebase/firestore";

export type GenericDataType = {
  id: string; // Store unique id generated by server or frontend
  name: string; // Store name to show on frontend
  createdAt?: FieldValue; // Store server time of firestore when data was created
  updatedAt?: FieldValue; // Store server time of firestore when data was updated
  updatedBy?: string; // Store email of the user who updates the data
  createdBy?: string; // Store email of the user who creates the data
};

export type CommonType = Partial<{
  label: ReactNode;
  value: string;
}>;
